// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjOqzI1xpKu5yW_MGMmTLLXUxwtWe1u4',
    appId: '1:614898179055:web:84fab582742d695003b41a',
    messagingSenderId: '614898179055',
    projectId: 'siries',
    authDomain: 'siries.firebaseapp.com',
    storageBucket: 'siries.firebasestorage.app',
    measurementId: 'G-REZB835EF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBoZzx-u1FpsacWfHOCU0tallxYzwQnI',
    appId: '1:614898179055:android:dcda270543fcad0903b41a',
    messagingSenderId: '614898179055',
    projectId: 'siries',
    storageBucket: 'siries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBaFw_-4_3IAuz1j1n1YMEOM9MPc-5q2E',
    appId: '1:614898179055:ios:c0869b595f2bf01903b41a',
    messagingSenderId: '614898179055',
    projectId: 'siries',
    storageBucket: 'siries.firebasestorage.app',
    iosBundleId: 'com.example.siriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBaFw_-4_3IAuz1j1n1YMEOM9MPc-5q2E',
    appId: '1:614898179055:ios:c0869b595f2bf01903b41a',
    messagingSenderId: '614898179055',
    projectId: 'siries',
    storageBucket: 'siries.firebasestorage.app',
    iosBundleId: 'com.example.siriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjOqzI1xpKu5yW_MGMmTLLXUxwtWe1u4',
    appId: '1:614898179055:web:e2b9e6c2c84decba03b41a',
    messagingSenderId: '614898179055',
    projectId: 'siries',
    authDomain: 'siries.firebaseapp.com',
    storageBucket: 'siries.firebasestorage.app',
    measurementId: 'G-49L72E4F3P',
  );
}
